name: premio project deployement

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DDEV_HOST }}
          username: ${{ secrets.DDEV_USER }}
          port: ${{ secrets.DDEV_PORT }}
          # password: ${{ secrets.DDEV_PASS }}
          KEY: ${{ secrets.DDEV_SSH_SECRET_KEY }}
          source: "."
          target: "/var/www/dummy"

      - name: executing laravel deployement commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DDEV_HOST }}
          username: ${{ secrets.DDEV_USER }}
          port: ${{ secrets.DDEV_PORT }}
          # password: ${{ secrets.PLS_DDEV_PASS }}
          KEY: ${{ secrets.DDEV_SSH_SECRET_KEY }}
          script: |
            # cd /var/www/html/dummy
            cd /var/www/html/dummy
            echo "creating env file...."
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            echo "executing composer install...."
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            echo "Generating key..."
            php artisan key:generate
            echo "Granting directory permissions..."
            chmod -R 777 bootstrap/
            chmod -R 777 storage/
            chmod -R 777 public/
            echo "running migration"
            php artisan migrate
            php artisan l5-swagger:generate
            echo "run seed"
            php artisan db:seed
            #echo "finally unit testing..."
            #vendor/bin/phpunit
            echo "Cache clear..."
            php artisan cache:clear
            echo "done...."
